In [1]:
import pandas as pd
import time

In [2]:
print("Langkah 1: Memuat Dataset (Versi Full CSV)...")

try:
    # 1. Memuat IndoNLP
    print("-> Memuat IndoNLP...")
    start_time = time.time()
    # GANTI path di bawah dengan path file IndoNLP.csv milik Anda
    df_indonlp = pd.read_csv("/kaggle/input/datasets/ahmadtaufanhidayat/indonlp/IndoNLP.csv", on_bad_lines='skip', low_memory=False)
    print(f"✅ IndoNLP berhasil dimuat. (Waktu: {time.time() - start_time:.2f} detik)")
    
    # 2. Memuat NusaX
    print("-> Memuat NusaX...")
    start_time = time.time()
    # GANTI path di bawah dengan path file NusaX CSV milik Anda
    df_nusax = pd.read_csv("/kaggle/input/datasets/ahmadtaufanhidayat/csv-dataset/Dataset_NusaX_Jawa_Indo.csv", on_bad_lines='skip', low_memory=False, sep=';')
    print(f"✅ NusaX berhasil dimuat. (Waktu: {time.time() - start_time:.2f} detik)")
    
    # 3. Memuat SeaCrowd
    print("-> Memuat SeaCrowd...")
    start_time = time.time()
    # GANTI path di bawah dengan path file SeaCrowd CSV milik Anda
    df_seacrowd = pd.read_csv("/kaggle/input/datasets/ahmadtaufanhidayat/csv-dataset/dataset_seacrowd_jawa_indo_mentah.csv", on_bad_lines='skip', low_memory=False, sep=';')
    print(f"✅ SeaCrowd berhasil dimuat. (Waktu: {time.time() - start_time:.2f} detik)")

    print("\n🎉 SEMUA DATASET BERHASIL DIMUAT DENGAN CEPAT!")

except Exception as e:
    print(f"\n❌ Terjadi kesalahan: {e}")

Langkah 1: Memuat Dataset (Versi Full CSV)...
-> Memuat IndoNLP...
✅ IndoNLP berhasil dimuat. (Waktu: 0.06 detik)
-> Memuat NusaX...
✅ NusaX berhasil dimuat. (Waktu: 0.02 detik)
-> Memuat SeaCrowd...

❌ Terjadi kesalahan: 'utf-8' codec can't decode byte 0xe9 in position 50: invalid continuation byte

In [3]:
# Memuat pustaka pandas dan time untuk menghitung kecepatan proses
import pandas as pd
import time

print("Langkah 1: Memuat Dataset (Versi Full CSV dengan Fix Encoding)...")

try:
    # 1. Memuat IndoNLP
    print("-> Memuat IndoNLP...")
    start_time = time.time()
    # GANTI path di bawah dengan path file IndoNLP.csv milik Anda
    df_indonlp = pd.read_csv("/kaggle/input/datasets/ahmadtaufanhidayat/indonlp/IndoNLP.csv", on_bad_lines='skip', low_memory=False)
    print(f"✅ IndoNLP berhasil dimuat. (Waktu: {time.time() - start_time:.2f} detik)")
    
    # 2. Memuat NusaX
    print("-> Memuat NusaX...")
    start_time = time.time()
    # GANTI path di bawah dengan path file NusaX CSV milik Anda
    df_nusax = pd.read_csv("/kaggle/input/datasets/ahmadtaufanhidayat/csv-dataset/Dataset_NusaX_Jawa_Indo.csv", on_bad_lines='skip', low_memory=False, sep=';')
    print(f"✅ NusaX berhasil dimuat. (Waktu: {time.time() - start_time:.2f} detik)")
    
    # 3. Memuat SeaCrowd (Dengan perbaikan encoding)
    print("-> Memuat SeaCrowd...")
    start_time = time.time()
    # GANTI path di bawah dengan path file SeaCrowd CSV milik Anda
    # Menambahkan parameter encoding='latin-1' untuk mengatasi karakter aksen Jawa
    df_seacrowd = pd.read_csv("/kaggle/input/datasets/ahmadtaufanhidayat/csv-dataset/dataset_seacrowd_jawa_indo_mentah.csv", on_bad_lines='skip', low_memory=False, encoding='latin-1', sep=';')
    print(f"✅ SeaCrowd berhasil dimuat. (Waktu: {time.time() - start_time:.2f} detik)")

    print("\n🎉 SEMUA DATASET BERHASIL DIMUAT DENGAN AMAN!")

except Exception as e:
    print(f"\n❌ Terjadi kesalahan: {e}")

Langkah 1: Memuat Dataset (Versi Full CSV dengan Fix Encoding)...
-> Memuat IndoNLP...
✅ IndoNLP berhasil dimuat. (Waktu: 0.02 detik)
-> Memuat NusaX...
✅ NusaX berhasil dimuat. (Waktu: 0.01 detik)
-> Memuat SeaCrowd...
✅ SeaCrowd berhasil dimuat. (Waktu: 0.09 detik)

🎉 SEMUA DATASET BERHASIL DIMUAT DENGAN AMAN!

In [4]:
print("Langkah 2: Menyaring dan Menyeragamkan Nama Kolom...")

# Memproses IndoNLP (Ambil kolom indonesian dan javanese)
df_indonlp = df_indonlp[['indonesian', 'javanese']]
df_indonlp = df_indonlp.rename(columns={'indonesian': 'indonesia', 'javanese': 'jawa'})

# Memproses NusaX
# Ubah 'kolom_indo_nusax' dan 'kolom_jawa_nusax' sesuai nama kolom asli di file Anda
df_nusax = df_nusax.rename(columns={'text_1': 'indonesia', 'text_2': 'jawa'})
df_nusax = df_nusax[['indonesia', 'jawa']]

# Memproses Seacrowd
# Ubah 'kolom_indo_seacrowd' dan 'kolom_jawa_seacrowd' sesuai nama kolom asli di file Anda
df_seacrowd = df_seacrowd.rename(columns={'text_1': 'indonesia', 'text_2': 'jawa'})
df_seacrowd = df_seacrowd[['indonesia', 'jawa']]

print("Kolom berhasil diseragamkan.")

Langkah 2: Menyaring dan Menyeragamkan Nama Kolom...
Kolom berhasil diseragamkan.

In [5]:
print("Kolom IndoNLP :", df_indonlp.columns.tolist())
print("Kolom NusaX   :", df_nusax.columns.tolist())
print("Kolom SeaCrowd:", df_seacrowd.columns.tolist())

Kolom IndoNLP : ['indonesia', 'jawa']
Kolom NusaX   : ['indonesia', 'jawa']
Kolom SeaCrowd: ['indonesia', 'jawa']

**Menggabungkan Data**

In [6]:
print("Langkah 3: Menggabungkan Semua Dataset...")

# Menggabungkan ketiga dataset ke bawah
df_gabungan = pd.concat([df_indonlp, df_nusax, df_seacrowd], ignore_index=True)

print(f"Total baris saat ini (sebelum dibersihkan): {len(df_gabungan)} baris")

Langkah 3: Menggabungkan Semua Dataset...
Total baris saat ini (sebelum dibersihkan): 12959 baris

**Pembersihan Data (Data Cleaning)**

In [7]:
print("Langkah 4: Membersihkan Data (Menghapus Kosong dan Duplikat)...")

# Menghapus baris yang kosong (NaN)
df_bersih = df_gabungan.dropna()

# Menghapus duplikat agar model tidak overfitting
df_bersih = df_bersih.drop_duplicates(subset=['indonesia', 'jawa'])

print(f"Total baris bersih yang siap digunakan: {len(df_bersih)} baris")

Langkah 4: Membersihkan Data (Menghapus Kosong dan Duplikat)...
Total baris bersih yang siap digunakan: 12952 baris

**Menyimpan Hasil**

In [8]:
print("Langkah 5: Menyimpan Hasil Akhir...")

# Menyimpan data bersih ke dalam file CSV baru
nama_file_output = "dataset_tahap1_bersih.csv"
df_bersih.to_csv(nama_file_output, index=False)

print(f"Data bersih berhasil disimpan sebagai: {nama_file_output}")

# Menampilkan 5 data teratas untuk memastikan hasilnya rapi
df_bersih.head()

Langkah 5: Menyimpan Hasil Akhir...
Data bersih berhasil disimpan sebagai: dataset_tahap1_bersih.csv

,indonesia,jawa
0,"Dekat dengan hotel saya menginap, hanya ditemp...","Cepak saka hotelku nginep, namung digawa mlaku..."
1,"Iya benar, dia sedang jaga warung.","Iya bener, deknen lagi jaga warung."
2,Kangkungnya lumayan tapi kepiting saus padangn...,Kangkunge lumayan nanging yuyu saus padange ng...
3,Bertempat di braga city walk yang satu gedung ...,Manggon nang braga city walk sing sak gedung k...
4,Gianyar terima bantuan sosial 2018 sebesar rp ...,Gianyar nompo bantuan sosial 2018 gedene rp 44...

In [9]:
!pip install datasets -q

**Mengambil Dataset Tatoeba (Indonesia - Jawa)**

**Download Dataset OPUS - Tatoeba**

In [10]:
print("Langkah 6: Mendownload file ZIP Tatoeba dari server CSC Finlandia...")

# Mengunduh file menggunakan link direct storage yang valid
!wget -O tatoeba_id_jv.zip "https://object.pouta.csc.fi/OPUS-Tatoeba/v2023-04-12/moses/id-jv.txt.zip"

print("\n✅ Download selesai! File 'tatoeba_id_jv.zip' yang asli sudah aman di folder.")

Langkah 6: Mendownload file ZIP Tatoeba dari server CSC Finlandia...
--2026-06-20 03:54:50--  https://object.pouta.csc.fi/OPUS-Tatoeba/v2023-04-12/moses/id-jv.txt.zip
Resolving object.pouta.csc.fi (object.pouta.csc.fi)... 86.50.254.18, 86.50.254.19
Connecting to object.pouta.csc.fi (object.pouta.csc.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13786 (13K) [application/zip]
Saving to: ‘tatoeba_id_jv.zip’

tatoeba_id_jv.zip   100%[===================>]  13.46K  --.-KB/s    in 0.006s

2026-06-20 03:54:50 (2.19 MB/s) - ‘tatoeba_id_jv.zip’ saved [13786/13786]


✅ Download selesai! File 'tatoeba_id_jv.zip' yang asli sudah aman di folder.

**Mengekstrak & Memeriksa Nama File Hasil Ekstrak**

In [11]:
import zipfile
import os

print("Langkah 7: Mengekstrak ZIP via Python murni...")

# Melakukan ekstraksi file secara aman ke folder saat ini ('.')
with zipfile.ZipFile("tatoeba_id_jv.zip", "r") as zip_ref:
    zip_ref.extractall(".")
print("✅ Proses ekstraksi selesai 100%!")

print("\nDaftar file teks terjemahan yang berhasil keluar:")
# Menampilkan file yang mengandung nama Tatoeba untuk kita intip namanya
for nama_file in os.listdir('.'):
    if "Tatoeba" in nama_file and not nama_file.endswith(".zip"):
        print(f"📄 {nama_file}")

Langkah 7: Mengekstrak ZIP via Python murni...
✅ Proses ekstraksi selesai 100%!

Daftar file teks terjemahan yang berhasil keluar:
📄 Tatoeba.id-jv.id
📄 Tatoeba.id-jv.xml
📄 Tatoeba.id-jv.jv

**Membaca ke Pandas DataFrame & Pembersihan**

In [12]:
import pandas as pd

print("Langkah 8: Membaca file teks paralel ke Pandas DataFrame...")

# KODE PROTEKSI: Masukkan nama file yang muncul dari output Cell 7 di atas.
# Secara standar OPUS, namanya adalah format di bawah ini:
file_indonesia = "Tatoeba.id-jv.id"
file_jawa = "Tatoeba.id-jv.jv"

try:
    # 1. Membaca file teks Indonesia
    with open(file_indonesia, "r", encoding="utf-8") as f_id:
        lines_id = [line.strip() for line in f_id.readlines()]

    # 2. Membaca file teks Jawa
    with open(file_jawa, "r", encoding="utf-8") as f_jv:
        lines_jv = [line.strip() for line in f_jv.readlines()]

    # 3. Menyatukan kedua list menjadi tabel DataFrame
    df_tatoeba = pd.DataFrame({
        'indonesia': lines_id,
        'jawa': lines_jv
    })
    print(f"- Total data awal dari Tatoeba: {len(df_tatoeba)} baris")

    # 4. Melakukan pembersihan data kosong dan duplikat internal
    df_tatoeba = df_tatoeba.dropna()
    df_tatoeba = df_tatoeba.drop_duplicates(subset=['indonesia', 'jawa'])

    print(f"✅ Selesai! Total data BERSIH dari Tatoeba: {len(df_tatoeba)} baris")
    
    # Menampilkan 5 data teratas untuk memastikan teksnya selaras
    display(df_tatoeba.head())

except FileNotFoundError:
    print("❌ Error: File teks tidak ditemukan!")
    print("Buka kembali output Cell 7, lihat nama file asli yang keluar, lalu sesuaikan variabel 'file_indonesia' dan 'file_jawa' di cell ini.")

Langkah 8: Membaca file teks paralel ke Pandas DataFrame...
- Total data awal dari Tatoeba: 226 baris
✅ Selesai! Total data BERSIH dari Tatoeba: 222 baris

,indonesia,jawa
0,Jangan menebang pohon yang masih muda.,Aja negori wit sing isih enom.
1,Kamu sudah mandi apa belum?,Kowé wis adus apa durung?
2,Kamu tampaknya belum tahu rasa dipatil lele.,Kowé sajaké durung ngerti rasané dipatil lélé.
3,Kenapa kamu tidak tanya sendiri ke dia?,Ngapa kowé ora takon dhéwé nang dhèwèké?
4,Jangan merokok.,Aja ngudud.

**Mendownload File ZIP Tanzil (Al-Quran Parallel)**

In [13]:
print("Langkah 12: Mendownload file ZIP WikiMatrix dari server CSC Finlandia...")

# Mengunduh file zip WikiMatrix id-jv
!wget -O wikimatrix_id_jv.zip "https://object.pouta.csc.fi/OPUS-WikiMatrix/v1/moses/id-jv.txt.zip"

print("\n✅ Download selesai! File 'wikimatrix_id_jv.zip' sudah aman di folder.")

Langkah 12: Mendownload file ZIP WikiMatrix dari server CSC Finlandia...
--2026-06-20 03:54:50--  https://object.pouta.csc.fi/OPUS-WikiMatrix/v1/moses/id-jv.txt.zip
Resolving object.pouta.csc.fi (object.pouta.csc.fi)... 86.50.254.18, 86.50.254.19
Connecting to object.pouta.csc.fi (object.pouta.csc.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2320899 (2.2M) [application/zip]
Saving to: ‘wikimatrix_id_jv.zip’

wikimatrix_id_jv.zi 100%[===================>]   2.21M  8.32MB/s    in 0.3s

2026-06-20 03:54:51 (8.32 MB/s) - ‘wikimatrix_id_jv.zip’ saved [2320899/2320899]


✅ Download selesai! File 'wikimatrix_id_jv.zip' sudah aman di folder.

**Mengekstrak & Mendeteksi Nama File Teks CCMatrix**

In [14]:
import zipfile
import os

print("Langkah 13: Mengekstrak ZIP WikiMatrix via Python murni...")

# Mengekstrak file zip ke folder saat ini ('.')
with zipfile.ZipFile("wikimatrix_id_jv.zip", "r") as zip_ref:
    zip_ref.extractall(".")
print("✅ Proses ekstraksi WikiMatrix selesai 100%!")

print("\nDaftar file teks WikiMatrix yang berhasil keluar:")
for nama_file in os.listdir('.'):
    if "WikiMatrix" in nama_file and not nama_file.endswith(".zip"):
        print(f"📄 {nama_file}")

Langkah 13: Mengekstrak ZIP WikiMatrix via Python murni...
✅ Proses ekstraksi WikiMatrix selesai 100%!

Daftar file teks WikiMatrix yang berhasil keluar:
📄 WikiMatrix.id-jv.jv
📄 WikiMatrix.id-jv.xml
📄 WikiMatrix.id-jv.id

**Membaca ke Pandas, Pembersihan, dan Pemotongan (Slicing) Top Data**

In [15]:
import pandas as pd

print("Langkah 14: Membaca file teks WikiMatrix ke Pandas DataFrame...")

# Nama file standar dari proyek OPUS WikiMatrix
file_indonesia = "WikiMatrix.id-jv.id"
file_jawa = "WikiMatrix.id-jv.jv"

try:
    # 1. Membaca file teks
    with open(file_indonesia, "r", encoding="utf-8") as f_id:
        lines_id = [line.strip() for line in f_id.readlines()]

    with open(file_jawa, "r", encoding="utf-8") as f_jv:
        lines_jv = [line.strip() for line in f_jv.readlines()]

    # 2. Satukan ke DataFrame Pandas
    df_wikimatrix = pd.DataFrame({
        'indonesia': lines_id,
        'jawa': lines_jv
    })
    print(f"- Total data mentah WikiMatrix: {len(df_wikimatrix)} baris")

    # 3. Bersihkan dari baris kosong dan duplikat internal
    df_wikimatrix = df_wikimatrix.dropna()
    df_wikimatrix = df_wikimatrix.drop_duplicates(subset=['indonesia', 'jawa'])
    
    # 4. Buang juga baris yang isinya sama persis (jika ada) untuk jaga-jaga
    df_wikimatrix = df_wikimatrix[df_wikimatrix['indonesia'] != df_wikimatrix['jawa']]
    print(f"✅ Selesai! Total data BERSIH dari WikiMatrix: {len(df_wikimatrix)} baris")
    
    # Menampilkan 10 data teratas hasil akhir WikiMatrix
    display(df_wikimatrix.head(10))

except FileNotFoundError:
    print("❌ Error: File teks WikiMatrix tidak ditemukan! Pastikan urutan cell benar.")

Langkah 14: Membaca file teks WikiMatrix ke Pandas DataFrame...
- Total data mentah WikiMatrix: 19596 baris
✅ Selesai! Total data BERSIH dari WikiMatrix: 19595 baris

,indonesia,jawa
0,Anak-anak kemudian meninggalkan dan Norman bek...,Para warga pada metu karo nggowoni sampah sing...
1,"Lalu tahanlah diri dari sholat, karena sesungg...",Pramila putranipun ingkang asma Drestarastra-r...
2,Tidakkah Allah lebih mengetahui tentang golong...,Sira banjur didangu sarupaning kabungahan papa...
3,Demikian pula manusia memiliki kemampuan terse...,Temoné ing kana wujud prasasti watu.
4,"""Ivan Lanin, Bangga Berbahasa Indonesia"".","""Ivan Lanin, Bangga Berbahasa Indonésia""."
5,"Sebelum Perang Dunia II, 14 radio komersial da...","Sadèrèngipun Perang Dunia II, 14 radio komersi..."
6,Malu (Aku) Jadi Orang Indonesia.,Malu (Aku) Jadi Orang Indonésia.
7,Demikian pula dengan Sejumlah Perkutut Buat Ba...,Semono uga ing Sejumlah Perkutut buat Bapak.
8,Kemudian mereka menikah.,"""Ya, mereka bertunangan."
9,Kriteria itu harus diterapkan pada konsekuensi...,Kriteria punika kedah dipunterapaken ing konse...

**Penyaringan Emas Murni WikiMatrix**

In [16]:
import pandas as pd
import string
import re

print("Langkah 15: Meluncurkan Mesin Penyaring Emas untuk WikiMatrix...")

# Fungsi pembantu untuk membongkar kembar gaib (spasi tak terlihat, beda kapital, dll)
def normalisasi_total(teks):
    if not isinstance(teks, str):
        return ""
    teks = teks.lower().strip()
    # Hapus semua tanda baca
    teks = teks.translate(str.maketrans('', '', string.punctuation))
    # Hapus semua spasi agar menjadi satu kata dempet
    return "".join(teks.split())

# Membuat copy data dari hasil Langkah 14 kemarin
df_saring = df_wikimatrix.copy()

# LAPIS 1: Saring Kembar Gaib via Normalisasi
df_saring['indo_norm'] = df_saring['indonesia'].apply(normalisasi_total)
df_saring['jawa_norm'] = df_saring['jawa'].apply(normalisasi_total)
df_saring = df_saring[df_saring['indo_norm'] != df_saring['jawa_norm']]

# LAPIS 2: Wajib mengandung kata kunci Bahasa Jawa asli
kata_kunci_jawa = [
    'sing', 'ing', 'lan', 'saka', 'saking', 'wonten', 'ora', 'mboten', 
    'yaiku', 'iki', 'kuwi', 'dipun', 'piyambak', 'nanging', 'kagem', 'ipun',
    'utawa', 'marang', 'menika', 'sawise', 'amarga', 'mung', 'kalebu', 'iku'
]
# Membuat regex pattern kata utuh (\b memastikan kata berdiri sendiri, bukan bagian dari kata lain)
pattern_jawa = '|'.join([r'\b' + kata + r'\b' for kata in kata_kunci_jawa])
df_saring = df_saring[df_saring['jawa'].str.lower().str.contains(pattern_jawa, regex=True, na=False)]

# LAPIS 3: Blacklist kata hubung Indonesia yang sering mengontaminasi kolom Jawa
kata_larangan_indo = ['adalah', 'yang', 'dengan', 'bahwa']
pattern_indo = '|'.join([r'\b' + kata + r'\b' for kata in kata_larangan_indo])
df_saring = df_saring[~df_saring['jawa'].str.lower().str.contains(pattern_indo, regex=True, na=False)]

# Membersihkan kolom bantu normalisasi dan mereset index
df_wikimatrix_clean = df_saring.drop(columns=['indo_norm', 'jawa_norm']).reset_index(drop=True)

print(f"📊 Dari 19.595 data WikiMatrix yang kotor...")
print(f"✅ Berhasil disaring ketat menjadi: {len(df_wikimatrix_clean)} baris EMAS MURNI!")

# Menampilkan 10 data teratas untuk pembuktian kualitas
display(df_wikimatrix_clean.head(10))

Langkah 15: Meluncurkan Mesin Penyaring Emas untuk WikiMatrix...
📊 Dari 19.595 data WikiMatrix yang kotor...
✅ Berhasil disaring ketat menjadi: 16793 baris EMAS MURNI!

,indonesia,jawa
0,Anak-anak kemudian meninggalkan dan Norman bek...,Para warga pada metu karo nggowoni sampah sing...
1,Tidakkah Allah lebih mengetahui tentang golong...,Sira banjur didangu sarupaning kabungahan papa...
2,Demikian pula manusia memiliki kemampuan terse...,Temoné ing kana wujud prasasti watu.
3,"Sebelum Perang Dunia II, 14 radio komersial da...","Sadèrèngipun Perang Dunia II, 14 radio komersi..."
4,Demikian pula dengan Sejumlah Perkutut Buat Ba...,Semono uga ing Sejumlah Perkutut buat Bapak.
5,Kriteria itu harus diterapkan pada konsekuensi...,Kriteria punika kedah dipunterapaken ing konse...
6,Ia menyebutkan ayat ke-27 dalam surah Ar-Rahman.,Jenengé disebutake kaping 27 ing Al-Quran.
7,Ini mengakomodasi tradisi panjang dari aturan ...,Punika ngakomodasi tradisi panjang saking atur...
8,Surah Al-Lahab atau Al-Massad adalah surat ke-...,Surah Al-Lahab utawa Al-Masad iku surat angka ...
9,"Menurut anggapan Persatuan Opera Amerika, Rigo...","Miturut anggapan Persatuan Opera Amérika, Rigo..."

**Penggabungan Akbar & Ekspor Final ke CSV**

In [17]:
print("Langkah 16: Memulai proses Penggabungan Dataset...")

# 1. Memuat Dataset Tahap 1 yang sudah bersih sebelumnya
df_tahap1 = pd.read_csv("dataset_tahap1_bersih.csv")
print(f"- Data Tahap 1 (NusaX + SeaCrowd + IndoNLP): {len(df_tahap1)} baris")

# 2. Mengambil Data Tatoeba yang tersimpan di memori
print(f"- Data Tambahan Tatoeba: {len(df_tatoeba)} baris")

# 3. Memotong Data WikiMatrix (Skip baris 0 & 1 yang ngaco, ambil sisa secukupnya)
# Kita ambil sekitar 6.900 baris dari baris ke-2 untuk menggenapi target 20.000
df_wiki_slice = df_wikimatrix_clean.iloc[2:6902].reset_index(drop=True)
print(f"- Data Tambahan WikiMatrix (Sudah dipotong & skip baris ngaco): {len(df_wiki_slice)} baris")

# 4. Menggabungkan ketiga DataFrame secara vertikal
df_final = pd.concat([df_tahap1, df_tatoeba, df_wiki_slice], ignore_index=True)

# 5. Proteksi Akhir: Bersihkan duplikat total yang mungkin tercipta antar-dataset
df_final = df_final.dropna()
df_final = df_final.drop_duplicates(subset=['indonesia', 'jawa'])

print(f"\n🚀 TOTAL DATA FINAL YANG BERHASIL DIKUMPULKAN: {len(df_final)} BARIS!")

# 6. Menyimpan langsung menjadi file fisik CSV di folder kerja Kaggle
df_final.to_csv("dataset_final_20k.csv", index=False)
print("💾 File 'dataset_final_20k.csv' sukses dibuat dan siap digunakan untuk training model NLLB/MarianMT!")

Langkah 16: Memulai proses Penggabungan Dataset...
- Data Tahap 1 (NusaX + SeaCrowd + IndoNLP): 12952 baris
- Data Tambahan Tatoeba: 222 baris
- Data Tambahan WikiMatrix (Sudah dipotong & skip baris ngaco): 6900 baris

🚀 TOTAL DATA FINAL YANG BERHASIL DIKUMPULKAN: 20074 BARIS!
💾 File 'dataset_final_20k.csv' sukses dibuat dan siap digunakan untuk training model NLLB/MarianMT!

**Membersihkan Simbol **

In [18]:
print("Mulai membersihkan simbol Mojibake (Î± -> α) pada dataset final...")

# 1. Load dataset final yang kemarin sudah jadi
df_fix = pd.read_csv("dataset_final_20k.csv")

# 2. Fungsi sakti untuk mengembalikan kacamata baca ke UTF-8
def perbaiki_mojibake(teks):
    if not isinstance(teks, str):
        return teks
    try:
        # Mengubah teks rusak Latin-1 kembali ke biner asli, lalu didecode ulang ke UTF-8
        return teks.encode('latin1').decode('utf-8')
    except:
        return teks

# 3. Terapkan fungsi ke kolom indonesia dan jawa
df_fix['indonesia'] = df_fix['indonesia'].apply(perbaiki_mojibake)
df_fix['jawa'] = df_fix['jawa'].apply(perbaiki_mojibake)

# 4. Overwrite (timpa) kembali ke file CSV yang sama
df_fix.to_csv("dataset_final_20k.csv", index=False)

print("✅ Selesai! Simbol rusak berhasil disembuhkan.")
print("Contoh teks yang tadinya rusak sekarang menjadi:")
# Menampilkan baris yang mengandung kata Centauri buat pembuktian
display(df_fix[df_fix['indonesia'].str.contains('Centauri', na=False, case=False)].head(1))

Mulai membersihkan simbol Mojibake (Î± -> α) pada dataset final...
✅ Selesai! Simbol rusak berhasil disembuhkan.
Contoh teks yang tadinya rusak sekarang menjadi:

,indonesia,jawa
14992,Semburan pada Proxima Centauri dapat mengikis ...,Semburan ing Proxima Centauri bisa ngikis atmo...

**Cek baris yang terbalik**

In [19]:
import re

print("Langkah Diagnostik 1: Mendeteksi Kolom yang Terbalik...")

# PENTING: Pastikan nama 'df_final' di bawah ini diganti sesuai dengan
# nama variabel DataFrame gabungan 20.000 baris yang ada di notebook lu sekarang.
df_audit = df_final.copy()

# Daftar kata kunci Bahasa Jawa unik (tidak ada di Bahasa Indonesia) sebagai sensor
kata_kunci_jawa = [
    'sing', 'ing', 'lan', 'saka', 'saking', 'wonten', 'ora', 'mboten', 
    'yaiku', 'iki', 'kuwi', 'dipun', 'piyambak', 'nanging', 'kagem', 'ipun',
    'utawa', 'marang', 'menika', 'sawise', 'amarga', 'mung', 'kalebu', 'iku'
]

# Membuat regex pattern untuk mencetak batas kata utuh (\b) agar lebih akurat
pattern_jawa = '|'.join([r'\b' + kata + r'\b' for kata in kata_kunci_jawa])

def hitung_kata_jawa(teks):
    if not isinstance(teks, str):
        return 0
    # Menghitung berapa banyak kata Jawa yang muncul (case-insensitive)
    matches = re.findall(pattern_jawa, teks.lower())
    return len(matches)

# Mulai menghitung bobot bahasa Jawa di kedua kolom
df_audit['skor_jawa_di_indo'] = df_audit['indonesia'].apply(hitung_kata_jawa)
df_audit['skor_jawa_di_jawa'] = df_audit['jawa'].apply(hitung_kata_jawa)

# Logika Terbalik: Jika komponen kata Jawa di kolom Indo lebih dominan
kondisi_terbalik = (df_audit['skor_jawa_di_indo'] > df_audit['skor_jawa_di_jawa']) & (df_audit['skor_jawa_di_indo'] > 0)
df_terbalik = df_audit[kondisi_terbalik]

print(f"\n📊 HASIL AUDIT KOLOM BAHASA:")
print(f"- Total seluruh data yang diperiksa : {len(df_audit)} baris")
print(f"- Terdeteksi POSISI TERBALIK         : {len(df_terbalik)} baris")

if len(df_terbalik) > 0:
    print("\n👀 Sampel 5 data yang terdeteksi TERBALIK oleh sistem:")
    display(df_terbalik[['indonesia', 'jawa']].head(5))
else:
    print("\n✅ Aman! Tidak ditemukan kolom yang terbalik pada sampel data ini.")

Langkah Diagnostik 1: Mendeteksi Kolom yang Terbalik...

📊 HASIL AUDIT KOLOM BAHASA:
- Total seluruh data yang diperiksa : 20074 baris
- Terdeteksi POSISI TERBALIK         : 7953 baris

👀 Sampel 5 data yang terdeteksi TERBALIK oleh sistem:

,indonesia,jawa
401,Roti-roti sing disajekne nggarai aku nostalgia...,Kue-kue yang disajikan bikin saya bernostalgia...
402,Ibu uwis tahu kerja ing grab indonesia,Ibu pernah bekerja di grab indonesia
403,Paling seneng banget mangan awan ing kene pith...,Paling suka banget makan siang di sini ayam sa...
405,Arep nggawe postingan sing isine ngedukasi pel...,Mau bikin postingan yang isinya mengedukasi cu...
406,Atusan omah ing medan kebanjiran,Ratusan rumah di medan terendam banjir

**Cek Simbol**

In [20]:
print("Langkah Diagnostik 2 (Revisi): Meluncurkan Detektor Karakter Agresif...")

# PENTING: Pastikan variabel 'df_final' sesuai dengan nama DataFrame gabungan 20.000 baris lu
df_audit2_rev = df_final.copy()

# POLA SAKTI (Whitelist Negasi):
# Mencari semua karakter yang BUKAN huruf (a-z, A-Z), BUKAN angka (0-9), 
# BUKAN spasi (\s), BUKAN tanda baca standar, dan BUKAN huruf aksen Jawa (é, è, É, È)
pattern_bukan_normal = r'[^a-zA-Z0-9\s.,\-?!()"\':;_\+=\[\]\{\}/\\&%\*@#<>éèÉÈ]'

def cek_karakter_aneh(teks):
    if not isinstance(teks, str):
        return False
    # Mengembalikan True jika ditemukan karakter liar di luar zona aman
    return bool(re.search(pattern_bukan_normal, teks))

# Memeriksa kolom indonesia dan jawa
df_audit2_rev['kotor_indo'] = df_audit2_rev['indonesia'].apply(cek_karakter_aneh)
df_audit2_rev['kotor_jawa'] = df_audit2_rev['jawa'].apply(cek_karakter_aneh)

kondisi_kotor_agresif = df_audit2_rev['kotor_indo'] | df_audit2_rev['kotor_jawa']
df_kotor_agresif = df_audit2_rev[kondisi_kotor_agresif]

print(f"\n📊 HASIL AUDIT KARAKTER (METODE AGRESIF):")
print(f"- Total seluruh data yang diperiksa       : {len(df_audit2_rev)} baris")
print(f"- Terdeteksi mengandung KARAKTER REWEL/RUSAK: {len(df_kotor_agresif)} baris")

if len(df_kotor_agresif) > 0:
    print("\n👀 Sampel 10 data yang berhasil dibongkar oleh Detektor Agresif:")
    display(df_kotor_agresif[['indonesia', 'jawa']].head(10))
else:
    print("\n✅ Bersih Sempurna! Tidak ada karakter aneh yang lolos dari sensor.")

Langkah Diagnostik 2 (Revisi): Meluncurkan Detektor Karakter Agresif...

📊 HASIL AUDIT KARAKTER (METODE AGRESIF):
- Total seluruh data yang diperiksa       : 20074 baris
- Terdeteksi mengandung KARAKTER REWEL/RUSAK: 600 baris

👀 Sampel 10 data yang berhasil dibongkar oleh Detektor Agresif:

,indonesia,jawa
462,Mundake presentase sing minat ride sharing ngg...,Meningkatnya presentase peminat ride sharing m...
945,Para siswa sing pinter ora seneng karo masalah...,Orangtua siswa terkesan âtidak peduliâ den...
993,"pawingkingipun , komite sekolah namung dados â...","Akibatnya , komite sekolah cuma menjadi âste..."
1072,âDAK dialokasikan dhateng Daerah tertentu ko...,âDAK dialokasikan kepada Daerah tertentu unt...
1099,"kaping kalih , indikator kemiskinan ingkang di...","Kedua , indikator kemiskinan yang dihasilkan p..."
1101,Biaya saking masing-masing upaya âsensus mas...,Biaya dari masing-masing upaya âsensus masya...
1568,rasukan saking keluarga miskin ing umumnya yai...,Pakaian dari keluarga miskin pada umumnya adal...
1718,"kajawi punika , ingah-ingah Ã¢â¬Âsuku sekawa...","Selain itu , ternak Ã¢â¬Âkaki empatÃ¢â¬Â m..."
1764,Alasan-alasan bentenipun meliputi Ã¢â¬Åotak ...,Alasan-alasan lainnya meliputi Ã¢â¬Åotak ber...
1883,Ã¢â¬ÅBidan mboten wonten ing panggen sanes n...,Ã¢â¬ÅBidan tidak berada di tempat bukan bera...

**Memperbaiki Permasalahan Kolom Terbalik**

In [21]:
print("Memulai Proses Pemulihan Kolom yang Terbalik...")

# Pastikan nama 'df_final' sesuai dengan nama DataFrame 20.074 baris lu saat ini
df_clean_kolom = df_final.copy()

# Kamus Mini Kata Kunci Jawa sebagai kompas penentu arah bahasa
kata_kunci_jawa = [
    'sing', 'ing', 'lan', 'saka', 'saking', 'wonten', 'ora', 'mboten', 
    'yaiku', 'iki', 'kuwi', 'dipun', 'piyambak', 'nanging', 'kagem', 'ipun',
    'utawa', 'marang', 'menika', 'sawise', 'amarga', 'mung', 'kalebu', 'iku'
]
pattern_jawa = '|'.join([r'\b' + kata + r'\b' for kata in kata_kunci_jawa])

def hitung_kata_jawa(teks):
    if not isinstance(teks, str):
        return 0
    return len(re.findall(pattern_jawa, teks.lower()))

# 1. Hitung distribusi bobot kata Jawa di kedua kolom
skor_indo = df_clean_kolom['indonesia'].apply(hitung_kata_jawa)
skor_jawa = df_clean_kolom['jawa'].apply(hitung_kata_jawa)

# 2. Kunci indeks baris yang posisinya terbalik
kondisi_terbalik = (skor_indo > skor_jawa) & (skor_indo > 0)
total_terbalik = kondisi_terbalik.sum()

# 3. EKSEKUSI SWAP: Tukar posisi konten kolom Indonesia dan Jawa secara simultan
# Penggunaan .values di akhir wajib dipasang agar Pandas tidak bingung menyinkronkan indeks saat ditukar
df_clean_kolom.loc[kondisi_terbalik, ['indonesia', 'jawa']] = df_clean_kolom.loc[kondisi_terbalik, ['jawa', 'indonesia']].values

print(f"\n⚡ ELEKTRO-SHOCK SELESAI!")
print(f"- Total baris yang berhasil diluruskan kembali: {total_terbalik} baris.")

# 4. SANITY CHECK (Validasi Ulang Hasil Pemulihan)
skor_indo_baru = df_clean_kolom['indonesia'].apply(hitung_kata_jawa)
skor_jawa_baru = df_clean_kolom['jawa'].apply(hitung_kata_jawa)
sisa_terbalik = ((skor_indo_baru > skor_jawa_baru) & (skor_indo_baru > 0)).sum()

print(f"- Sisa baris yang terbalik setelah diperbaiki  : {sisa_terbalik} baris.")

# 5. Update data utama lu dengan data yang kolomnya sudah lurus
df_final = df_clean_kolom.copy()
print("\n💾 Variabel 'df_final' resmi diperbarui dan siap ke tahap pembersihan simbol!")

Memulai Proses Pemulihan Kolom yang Terbalik...

⚡ ELEKTRO-SHOCK SELESAI!
- Total baris yang berhasil diluruskan kembali: 7953 baris.
- Sisa baris yang terbalik setelah diperbaiki  : 0 baris.

💾 Variabel 'df_final' resmi diperbarui dan siap ke tahap pembersihan simbol!

**Memperbaiki Permasalahan Simbol**

In [22]:
# Membuat salinan dari df_final yang kolomnya sudah lurus
df_clean_simbol = df_final.copy()

def bersihkan_mojibake_dan_simbol(teks):
    if not isinstance(teks, str):
        return teks
    
    # 1. Memperbaiki encoding huruf beraksen (contoh: Ã© kembali menjadi é)
    try:
        teks = teks.encode('latin1').decode('utf-8')
    except:
        pass
        
    # 2. Menghapus karakter Â akibat kesalahan pembacaan spasi khusus
    teks = teks.replace('Â', '')
    
    # 3. Menghapus karakter di luar whitelist (huruf, angka, tanda baca standar, dan aksen é/è)
    pattern_bukan_normal = r'[^a-zA-Z0-9\s.,\-?!()"\':;_\+=\[\]\{\}/\\&%\*@#<>éèÉÈ]'
    teks = re.sub(pattern_bukan_normal, '', teks)
    
    # 4. Mengubah spasi ganda atau berlebih menjadi spasi tunggal
    teks = re.sub(r'\s+', ' ', teks).strip()
    
    return teks

# Menerapkan fungsi pembersihan pada kedua kolom bahasa
df_clean_simbol['indonesia'] = df_clean_simbol['indonesia'].apply(bersihkan_mojibake_dan_simbol)
df_clean_simbol['jawa'] = df_clean_simbol['jawa'].apply(bersihkan_mojibake_dan_simbol)

# Validasi ulang menggunakan standar detektor agresif
def cek_karakter_aneh(teks):
    if not isinstance(teks, str):
        return False
    return bool(re.search(pattern_bukan_normal, teks))

kotor_indo = df_clean_simbol['indonesia'].apply(cek_karakter_aneh)
kotor_jawa = df_clean_simbol['jawa'].apply(cek_karakter_aneh)
sisa_kotor = (kotor_indo | kotor_jawa).sum()

print("Hasil Pembersihan Karakter:")
print(f"- Sisa baris yang mengandung karakter rusak: {sisa_kotor} baris")

# Memperbarui variabel utama jika sisa kotor sudah berkurang/nol
df_final = df_clean_simbol.copy()

Hasil Pembersihan Karakter:
- Sisa baris yang mengandung karakter rusak: 0 baris

**Menyimpan File format CSV**

In [23]:
df_final = df_final.dropna()
df_final = df_final.drop_duplicates(subset=['indonesia', 'jawa']).reset_index(drop=True)

# 2. Menyimpan DataFrame ke file CSV fisik di folder kerja Kaggle
nama_file = "dataset_final_bersih_20k.csv"
df_final.to_csv(nama_file, index=False)

print("Penyimpanan File Final Selesai:")
print(f"- Total baris akhir : {len(df_final)} baris")
print(f"- Nama file fisik   : {nama_file}")

Penyimpanan File Final Selesai:
- Total baris akhir : 20074 baris
- Nama file fisik   : dataset_final_bersih_20k.csv

**Deteksi Simbol Ã©|Ã¨|Ã**

In [24]:
df_check = pd.read_csv("dataset_final_bersih_20k.csv")

# 2. Pattern untuk mendeteksi karakter rusak spesifik aksen Jawa
pattern_rusak = r'\u00c3'

# 3. Memeriksa keberadaan simbol di kolom indonesia atau jawa
kondisi_rusak = df_check['indonesia'].str.contains(pattern_rusak, na=False, regex=True) | \
                df_check['jawa'].str.contains(pattern_rusak, na=False, regex=True)

df_terdeteksi = df_check[kondisi_rusak]

# 4. Menampilkan hasil statistik audit
print("Hasil Deteksi Karakter Rusak Aksen Jawa:")
print(f"- Total baris yang diperiksa      : {len(df_check)} baris")
print(f"- Total baris mengandung Ã©/Ã¨/Ã  : {len(df_terdeteksi)} baris")

# 5. Menampilkan sampel jika ditemukan
if len(df_terdeteksi) > 0:
    print("\nSampel 10 data terdeteksi:")
    display(df_terdeteksi[['indonesia', 'jawa']].head(10))

Hasil Deteksi Karakter Rusak Aksen Jawa:
- Total baris yang diperiksa      : 20074 baris
- Total baris mengandung Ã©/Ã¨/Ã  : 0 baris

In [25]:
df = pd.read_csv("dataset_final_bersih_20k.csv")

# 2. Mengatur konfigurasi Pandas agar tidak memotong teks panjang
pd.set_option("display.max_colwidth", None)

# 3. Mencari baris berdasarkan kata kunci dari sampel yang Anda temukan
# Ini memastikan program mencari data riil di dalam file Anda
kata_kunci = "linux|mota|korea|orgel"
df_target = df[
    df["indonesia"].str.contains(kata_kunci, na=False, case=False)
    | df["jawa"].str.contains(kata_kunci, na=False, case=False)
]

# 4. Mengambil 10 sampel pertama
df_10_sampel = df_target.head(10)

print(f"Menampilkan {len(df_10_sampel)} data asli secara FULL TEXT dari file CSV:\n")

# 5. Loop untuk mencetak string mentah tanpa batasan display tabel
for i, (idx, row) in enumerate(df_10_sampel.iterrows(), 1):
    print(f"=== BARIS KE-{i} (Index: {idx}) ===")
    print("INDONESIA :")
    print(row["indonesia"])
    print("JAWA      :")
    print(row["jawa"])
    print("-" * 60)

Menampilkan 10 data asli secara FULL TEXT dari file CSV:

=== BARIS KE-1 (Index: 2416) ===
INDONESIA :
dan bebannya tidak perlu diawasi, itu adalah fitur yang bagus.
JAWA      :
lan momotan panci sanes gampar polatanipun, anerusi ciri prayogi.
------------------------------------------------------------
=== BARIS KE-2 (Index: 4465) ===
INDONESIA :
Apakah ada pohon ara di tengah sungai dan ada beberapa kelenjar paling populer di dunia selalu menjadi pencipta rahmat dan rahmat Tuhan Yang Maha Kuasa
JAWA      :
Lagyeng tadhah rajah tamah ngenirken salir donyeki tan ana kang winikalpa singsal pingiling kal mingsil ngkang makaten ugi abangsa gomulralimun? wus man ing jalmotama papa cipta rahmat-jati tan kacambor lyan ing Hyang Kang Maha Mulya
------------------------------------------------------------
=== BARIS KE-3 (Index: 7586) ===
INDONESIA :
Selama ini BI mengakui adanya keterbatasan upaya penguatan kelembagaan yang menghambat pengembangan LKM
JAWA      :
sajrone iki BI ngakoni anane keterbatasan upaya pamotan kelembagaan sing menghambat pengembangan LKM
------------------------------------------------------------
=== BARIS KE-4 (Index: 7594) ===
INDONESIA :
Berbagai kegiatan penguatan kapasitas ini meliputi
JAWA      :
macem-macem kemempengan pamotan kapasitas iki meliputi
------------------------------------------------------------
=== BARIS KE-5 (Index: 7784) ===
INDONESIA :
1) Small Activities Scheme (SAS), 2) Program penguatan kelembagaan kredit mikro dan 3) Program Access
JAWA      :
1) Small Activities Scheme (SAS), 2) Program pamotan kelembagaan kredit mikro lan 3) Program Access
------------------------------------------------------------
=== BARIS KE-6 (Index: 8179) ===
INDONESIA :
Mungkin Kang Kabayan ini kepingin merasakan hangatnya sulutan rokok.
JAWA      :
Mbokmanawa Kang Kabayan iki kepengin ngrasakake angete slomotan rokok.
------------------------------------------------------------
=== BARIS KE-7 (Index: 13038) ===
INDONESIA :
Aku ingin pergi ke Korea.
JAWA      :
Aku péngin lunga menyang Koréa.
------------------------------------------------------------
=== BARIS KE-8 (Index: 13039) ===
INDONESIA :
Aku ingin pergi ke Korea.
JAWA      :
Aku arep budhal menyang Koréa.
------------------------------------------------------------
=== BARIS KE-9 (Index: 13811) ===
INDONESIA :
Gaon Chart adalah chart rekor nasional Korea Selatan.
JAWA      :
Gaon Chart ya iku chart rekor nasional Koréa Kidul.
------------------------------------------------------------
=== BARIS KE-10 (Index: 13942) ===
INDONESIA :
Perang Rusia-Jepang (10 Februari 1904 5 September 1905) adalah konflik yang sangat berdarah yang tumbuh dari persaingan antara ambisi imperialis Rusia dan Jepang di Manchuria dan Korea.
JAWA      :
Perang Rusia-Jepang (10 Fèbruari 1904 5 September 1905) iku konflik kang banget ngemu getih kang tuwuh saka saingan antarané ambisi imperialis Rusia lan Jepang ing Manchuria lan Koréa.
------------------------------------------------------------

**Memeriksa Kalimat berdialek**

In [26]:
import pandas as pd

# 1. Memuat file final
df = pd.read_csv("dataset_final_bersih_20k.csv")

# 2. Pola regex untuk mendeteksi huruf é, è, atau simbol biner awal \u00c3 (Ã)
pattern_dialek = r'[éè]|\u00c3'

# 3. Memeriksa kecocokan pada kolom indonesia atau kolom jawa
kondisi_dialek = df['indonesia'].str.contains(pattern_dialek, na=False, regex=True) | \
                 df['jawa'].str.contains(pattern_dialek, na=False, regex=True)

df_hasil = df[kondisi_dialek]

# 4. Menampilkan hasil statistik jumlah baris
print("Statistik Karakter Dialek Jawa:")
print(f"- Total seluruh baris diperiksa : {len(df)} baris")
print(f"- Total baris dengan dialek     : {len(df_hasil)} baris")

Statistik Karakter Dialek Jawa:
- Total seluruh baris diperiksa : 20074 baris
- Total baris dengan dialek     : 4717 baris

**Audit Rasio Panjang Kalimat**

In [27]:
df = pd.read_csv("dataset_final_bersih_20k.csv")

# 2. Fungsi untuk menghitung jumlah kata
def hitung_kata(teks):
    if not isinstance(teks, str):
        return 0
    return len(teks.split())

# 3. Menghitung jumlah kata di masing-masing kolom
df['len_indo'] = df['indonesia'].apply(hitung_kata)
df['len_jawa'] = df['jawa'].apply(hitung_kata)

# 4. Menghitung rasio panjang kata (perbandingan nilai maksimum dan minimum)
df['rasio_panjang'] = df.apply(
    lambda r: max(r['len_indo'], r['len_jawa']) / max(1, min(r['len_indo'], r['len_jawa'])), 
    axis=1
)

# 5. Menentukan ambang batas anomali (rasio panjang kata > 3.0 atau ada kolom kosong)
threshold = 3.0
kondisi_anomali = (df['rasio_panjang'] > threshold) | (df['len_indo'] == 0) | (df['len_jawa'] == 0)
df_anomali = df[kondisi_anomali]

print("Hasil Audit Rasio Panjang Kalimat:")
print(f"- Total seluruh baris diperiksa : {len(df)} baris")
print(f"- Terdeteksi rasio tidak wajar (> {threshold}x lipat): {len(df_anomali)} baris")

# 6. Menampilkan sampel jika ditemukan anomali panjang kalimat
if len(df_anomali) > 0:
    print("\nSampel data dengan perbedaan panjang ekstrem:")
    pd.set_option("display.max_colwidth", None)
    display(df_anomali[['indonesia', 'len_indo', 'jawa', 'len_jawa']].head(8))

Hasil Audit Rasio Panjang Kalimat:
- Total seluruh baris diperiksa : 20074 baris
- Terdeteksi rasio tidak wajar (> 3.0x lipat): 464 baris

Sampel data dengan perbedaan panjang ekstrem:

,indonesia,len_indo,jawa,len_jawa
3122,"Ulangi, jagalah, terima, Sucsma.",4,"Baleni sira sadaya, datan ana kara-kara, mula padha dinarima, susuwenan ing Hyang Suksma.",13
3709,Priye yen mungguh sireku apa tarbukane yayi Carikmudha aturira sumanggeng karsa pribadi kapantes kang sapunika menggah parimbon pangimpin,18,Kakeknya meninggal ketika mobilnya terluka.,5
4119,Ana rempeng anusup galagah rayung paketepan wana nipis anjor kewala lumaku nampak ara-ara iring katon dhukuhe sih adoh,18,Ada tetesan di tengah pelangi.,5
4719,Tuhan ganteng di hutan rusa cantik,6,Godha angker ing wana gung keh kidang menjangan kancil tuhu lwir sato ingonan kasenggol mring kang lumaris sadaya wus winangsitan,20
4895,Tan cinatur kang dinuteng margi kang kocapa krajan Wanamarta Kae Bayi Panurtane pan maksih rumbu-rumbu lagya senggang grahira kedhik wus catur madya wulan dennira angukut ingadhep pra arinira,28,Plot-plakat itu berbentuk jepitan dan pebas pyak-bem pung-brang,8
4896,Tangga desa parapatireki tercengang mendengar keruh asin di tangan semua pria yang tidur di tempat tidur sambil menyaksikan lentera kidal di tengah-tengah siksaan air mata mereka menyaksikan sandal,28,Ki Suwarja Wiradhustha lan Panukmi Panamar Kulawirya,7
4934,Tatanan sawahnya seperti engkau tubuh indah Lapa semedi dan mencoba membakar di,12,Lawan para sepuh sadayeki kewala neng kori peregolan Ki Bayi lon andikane ya wus prayoga iku rembugira methuk tatami lah wus sira mangkata mring Pagutan gupuh nulya Kae Kulawirya lengser saking ngarsa sigra dennya nuding marang rereyanira,37
4958,"Pindah ke desa Bustam, rumah Ki Arsengbudi,",7,Sawusira santri atur bekti nulya laju wau lampahira pra santri umiring kabeh selur marga supenuh luber amber maring ing sabin padamen sinasakan ka-abyaging laku belasah dhadhahing sawah,27

**Membuang baris yang panjang kalimatnya tidak sesuai**

In [28]:
df = pd.read_csv("dataset_final_20k.csv")

# 2. Fungsi hitung kata
def hitung_kata(teks):
    if not isinstance(teks, str):
        return 0
    return len(teks.split())

df['len_indo'] = df['indonesia'].apply(hitung_kata)
df['len_jawa'] = df['jawa'].apply(hitung_kata)

# 3. Menghitung rasio panjang kalimat
df['rasio_panjang'] = df.apply(
    lambda r: max(r['len_indo'], r['len_jawa']) / max(1, min(r['len_indo'], r['len_jawa'])), 
    axis=1
)

# 4. Menyaring baris dengan rasio aman (<= 3.0) dan tidak kosong
threshold = 3.0
kondisi_aman = (df['rasio_panjang'] <= threshold) & (df['len_indo'] > 0) & (df['len_jawa'] > 0)
df_clean_ratio = df[kondisi_aman].copy()

# 5. Menghapus kolom pembantu sebelum disimpan
df_clean_ratio = df_clean_ratio.drop(columns=['len_indo', 'len_jawa', 'rasio_panjang'])

# 6. Menyimpan kembali hasil filter ke file CSV
df_clean_ratio.to_csv("dataset_final_20k.csv", index=False)

print("Proses Eksekusi Pilihan B (Length Filtering) Selesai:")
print(f"- Total baris sebelum filter : {len(df)} baris")
print(f"- Total baris setelah filter : {len(df_clean_ratio)} baris")
print(f"- Jumlah baris yang dibuang  : {len(df) - len(df_clean_ratio)} baris")

Proses Eksekusi Pilihan B (Length Filtering) Selesai:
- Total baris sebelum filter : 20074 baris
- Total baris setelah filter : 19611 baris
- Jumlah baris yang dibuang  : 463 baris

**Meriksa Kolom yang memiliki kata khusus indonesia**

In [29]:
df_fix = pd.read_csv("dataset_final_20k.csv")

# 2. Kata kunci khas bahasa Indonesia sebagai detektor inversi sisa
kata_kunci_indo = ['yang', 'dan', 'di', 'dari', 'adalah', 'untuk', 'dengan', 'bahwa', 'dalam']
pattern_indo = '|'.join([r'\b' + kata + r'\b' for kata in kata_kunci_indo])

def hitung_kata_indo(teks):
    if not isinstance(teks, str):
        return 0
    return len(re.findall(pattern_indo, teks.lower()))

# 3. Hitung bobot kata Indonesia pada kedua kolom
skor_indo_col = df_fix['indonesia'].apply(hitung_kata_indo)
skor_jawa_col = df_fix['jawa'].apply(hitung_kata_indo)

# 4. Menentukan kondisi baris yang posisinya masih terbalik
kondisi_sisa_terbalik = (skor_jawa_col > skor_indo_col) & (skor_jawa_col > 0)
total_sisa_terbalik = kondisi_sisa_terbalik.sum()

# 5. Eksekusi penukaran posisi kolom secara simultan
if total_sisa_terbalik > 0:
    df_fix.loc[kondisi_sisa_terbalik, ['indonesia', 'jawa']] = df_fix.loc[kondisi_sisa_terbalik, ['jawa', 'indonesia']].values

# 6. Menyimpan kembali hasil perbaikan ke file CSV
df_fix.to_csv("dataset_fixx.csv", index=False)

print("Proses Eksekusi Pilihan A Selesai:")
print(f"- Total baris yang berhasil diluruskan: {total_sisa_terbalik} baris")
print(f"- Total baris akhir dataset           : {len(df_fix)} baris")

Proses Eksekusi Pilihan A Selesai:
- Total baris yang berhasil diluruskan: 8666 baris
- Total baris akhir dataset           : 19611 baris

**Memeriksa Kata untuk Orang, Tempat**

In [30]:
df_audit = pd.read_csv("dataset_fixx.csv")

def ekstrak_entitas_kapital(teks):
    if not isinstance(teks, str):
        return set()
    # Mengambil kata yang diawali huruf kapital dengan panjang minimal 2 karakter
    return set(re.findall(r'\b[A-Z][a-zA-Z0-9_]+\b', teks))

# 2. Menerapkan ekstraksi entitas pada kedua kolom
entitas_indo = df_audit['indonesia'].apply(ekstrak_entitas_kapital)
entitas_jawa = df_audit['jawa'].apply(ekstrak_entitas_kapital)

# 3. Logika deteksi: memiliki entitas di kedua kolom, tetapi tidak ada kecocokan sama sekali
kondisi_miskorelasi = []
for idx in range(len(df_audit)):
    set_i = entitas_indo.iloc[idx]
    set_j = entitas_jawa.iloc[idx]
    
    # Jika kedua kolom punya kata kapital, tapi tidak ada yang sama (irisan kosong)
    if len(set_i) > 0 and len(set_j) > 0 and len(set_i.intersection(set_j)) == 0:
        kondisi_miskorelasi.append(True)
    else:
        kondisi_miskorelasi.append(False)

df_miskorelasi = df_audit[kondisi_miskorelasi]

# 4. Menampilkan hasil statistik audit
print("Hasil Audit Miskorelasi Entitas:")
print(f"- Total seluruh baris diperiksa : {len(df_audit)} baris")
print(f"- Terdeteksi tidak sesuai makna : {len(df_miskorelasi)} baris")

# 5. Menampilkan sampel data yang tidak sesuai makna
if len(df_miskorelasi) > 0:
    print("\nSampel data yang terdeteksi miskorelasi:")
    pd.set_option("display.max_colwidth", None)
    display(df_miskorelasi[['indonesia', 'jawa']].head(5))

Hasil Audit Miskorelasi Entitas:
- Total seluruh baris diperiksa : 19611 baris
- Terdeteksi tidak sesuai makna : 5964 baris

Sampel data yang terdeteksi miskorelasi:

,indonesia,jawa
0,"Dekat dengan hotel saya menginap, hanya ditempuh jalan kaki, di sini banyak sekali pilihan makanannya, tempat yang luas, dan menyenangkan","Cepak saka hotelku nginep, namung digawa mlaku, ing kene akeh tenan pilian panganane, panggonane sing amba, lan nyenengake"
2,Kangkungnya lumayan tapi kepiting saus padangnya mengecewakan kami dikasih kepiting yang kopong akhir kami tidak makan keptingnya dan dikembalikan.,Kangkunge lumayan nanging yuyu saus padange nguciwakake dhewe dikei yuyu sing kopong akhir dhewe ora mangan yuyune lan dibalekake.
5,Ini salah satu contoh generasi yang tidak berguna. Bukan malah bermanfaat untuk bangsa tapi malah jadi sesuatu yang berbahaya bagi bangsa! Mantap jerat saja pakai uu ite,Iki salah siji conto generasi sing ora kangge. Ora malah migunani dinggo bangsa nanging malah dadi sesuatu sing mbahayani dinggo bangsa! Mantep jeraten ae nggawe uu ite
7,Memang lemah kita ini aku juga penakut sebenarnya,Tenan ringkih dhewe iki aku uga jiden saktenane
9,"Untuk menuju ke the peak memang terasa sangat jauh dari pusat kota bandung, dan aksesnya yang agak membingungkan dan jalan kecil berkelok-kelok. Namun anda mungkin tidak akan tersesat karena hampir di tiap belokan ada signage menuju ke the peak. Tempatnya sangat bagus untuk anda yang mencari suasana malam romantis, dengan pemandangan malam kota yang menakjubkan.","Kanggo menyang ing the peak mesthi wae karasa adoh banget saka pusat kutha bandung, lan aksese sing lumayan mbingungake lan dalan cilike mbelak-mbelok. Nanging kowe bisa ora bakal kesasar amarga meh ing saben enggokan ana tanda marang ing the peak. Panggonane apik banget kanggo kowe sing nggolek suasana mbengi romantis, kanthi pemandangan mbengi kutha sing apik tenan."

In [31]:

df_audit = pd.read_csv("dataset_fixx.csv")

kolom_ekstra = [col for col in df_audit.columns if col.lower() not in ['indonesia', 'jawa']]

# Menandai baris yang kolom ekstranya terisi (tidak kosong)
if kolom_ekstra:
    baris_kolom_ekstra = df_audit[kolom_ekstra].notna().any(axis=1)
else:
    baris_kolom_ekstra = pd.Series([False] * len(df_audit))

# 3. Memeriksa baris yang mengandung artifak bot WikiMatrix atau teks rusak sisa (\u00c3 = Ã)
# Pola mencari: '] ] ]', ',]', atau karakter 'Ã'
pattern_artifak = r'\] \] \]|,\]|\u00c3'
kondisi_artifak = df_audit['indonesia'].str.contains(pattern_artifak, na=False, regex=True) | \
                  df_audit['jawa'].str.contains(pattern_artifak, na=False, regex=True)

# 4. Menggabungkan semua indikasi eror struktur
kondisi_total_anomali = baris_kolom_ekstra | kondisi_artifak
df_anomali_struktur = df_audit[kondisi_total_anomali]

print("=== HASIL AUDIT TAHAP 1: ANOMALI STRUKTURAL ===")
print(f"- Total seluruh baris diperiksa     : {len(df_audit)} baris")
print(f"- Daftar kolom dalam file           : {list(df_audit.columns)}")
print(f"- Baris dengan struktur meluber     : {baris_kolom_ekstra.sum()} baris")
print(f"- Baris mengandung artifak bot/Ã    : {kondisi_artifak.sum()} baris")
print(f"- Total baris terinfeksi struktur   : {len(df_anomali_struktur)} baris")

# 5. Menampilkan sampel data yang rusak jika ditemukan
if len(df_anomali_struktur) > 0:
    print("\nSampel data anomali struktural:")
    pd.set_option("display.max_colwidth", None)
    columns_to_show = ['indonesia', 'jawa'] + kolom_ekstra
    display(df_anomali_struktur[columns_to_show].head(5))

=== HASIL AUDIT TAHAP 1: ANOMALI STRUKTURAL ===
- Total seluruh baris diperiksa     : 19611 baris
- Daftar kolom dalam file           : ['indonesia', 'jawa']
- Baris dengan struktur meluber     : 0 baris
- Baris mengandung artifak bot/Ã    : 17 baris
- Total baris terinfeksi struktur   : 17 baris

Sampel data anomali struktural:

,indonesia,jawa
1568,Pakaian dari keluarga miskin pada umumnya adalah â€pakaian cimolâ€ atau pakaian bekas,rasukan saking keluarga miskin ing umumnya yaiku Ã¢â¬Ârasukan cimolÃ¢â¬Â utawi rasukan bekas
1718,"Selain itu , ternak â€kaki empatâ€ merupakan salah satu usaha perekonomian masyarakat di NTT","kajawi punika , ingah-ingah Ã¢â¬Âsuku sekawanÃ¢â¬Â ngrupikaken salah satunggal upados perekonomian masyarakating NTT"
1764,Alasan-alasan lainnya meliputi â€œotak beratâ€ yang â€œkebandelanâ€ atau kenakalan remaja,Alasan-alasan bentenipun meliputi Ã¢â¬Åotak antebÃ¢â¬Â ingkang Ã¢â¬ÅkebandelanÃ¢â¬Â utawi kembelingan remaja
1883,â€œBidan tidak berada di tempat bukan berarti bidan meninggalkan desa,Ã¢â¬ÅBidan mboten wonten ing panggen sanes nduwe artos bidan mengker dhusun
13246,Keturunan mereka menjadi Pemangku di parahyangan (tempat suci) tersebut.,] ] ] Kacamatan Teon Nila Serua iku kacamatan ing Kabupatèn Maluku Tengah Provinsi Maluku.

In [32]:
df_audit2 = pd.read_csv("dataset_fixx.csv")

def ekstrak_angka(teks):
    if not isinstance(teks, str):
        return set()
    # Mengambil semua deretan angka (tahun, ayat, umur, dll)
    return set(re.findall(r'\d+', teks))

# 2. Hitung kecocokan angka antara kolom Indonesia dan Jawa
kondisi_angka_miskorelasi = []

for idx in range(len(df_audit2)):
    angka_indo = ekstrak_angka(df_audit2['indonesia'].iloc[idx])
    angka_jawa = ekstrak_angka(df_audit2['jawa'].iloc[idx])
    
    # Jika salah satu atau kedua kolom punya angka, tapi isinya beda total
    if (angka_indo or angka_jawa) and (angka_indo != angka_jawa):
        kondisi_angka_miskorelasi.append(True)
    else:
        kondisi_angka_miskorelasi.append(False)

df_cacat_makna = df_audit2[kondisi_angka_miskorelasi]

print("=== HASIL AUDIT TAHAP 2: KETIDAKSELARASAN ANGKA & MAKNA ===")
print(f"- Total seluruh baris diperiksa     : {len(df_audit2)} baris")
print(f"- Terdeteksi tidak sinkron (Angka)  : {len(df_cacat_makna)} baris")

# 3. Menampilkan sampel data untuk pembuktian
if len(df_cacat_makna) > 0:
    print("\nSampel data yang terdeteksi misaligned (Kasus Lukas/Ellen):")
    pd.set_option("display.max_colwidth", None)
    display(df_cacat_makna[['indonesia', 'jawa']].head(5))

=== HASIL AUDIT TAHAP 2: KETIDAKSELARASAN ANGKA & MAKNA ===
- Total seluruh baris diperiksa     : 19611 baris
- Terdeteksi tidak sinkron (Angka)  : 255 baris

Sampel data yang terdeteksi misaligned (Kasus Lukas/Ellen):

,indonesia,jawa
62,"Tempatnya cukup unik, rasa makanan standar, menu yang ditawarkan juga biasa, hanya saja yang menarik tempat dan keunikannya, cara memanggil pelayannya dengan memukul kentongan,. Aku pas ke sana pada malam hari, ditambah hujan, udaranya cukup dingin menusuk tulang, sempat menunggu kira-kira 15 menit untuk bisa dapat tempat, karena penuh blok pada saat itu. Disarankan kalau mau ke sana sore-sore.","Panggone lumayan unik, rasa panganane biasa, menu sing ditawakne uga biasa, mung panggone karo keunikane sing menarik, cara nyeluk pelayane nganggo nutuk kentongan,. Aku pas mrana wengi, diambah udan, udarane lumayan adem nyrusuk belung, sempet ngenteni kira-kira limolas menit ben iso entuk panggon, merga bek blok wektu iku. Disaranke lak sir mrana sore-sore."
456,"Wah pada karo aku iki masu nembe wae, paket freesom 1 aku hurung entek namung wis 40 ewu aku disedot perampok","Wah sama seperti saya ini mas barusan, paket freedom l saya belum habis tapi sudah dibebankan tarif internet perlu sampai pulsa sekitar 40 ribu saya disedot perampok"
493,"Paket saya juga sampai sekarang tidak sampai sampai sudah 5 hari statusnya dengan pengiriman courier jakarta, parah sekarang jne","Paketku uga sampek saiki ora teka-teka wis limang dina statuse nganggo pengiriman kurir jakarta, nemen saiki jne"
560,Untuk orang jogja sih malas kembali ke sana 2 kali. Cukup sekali. Masuk harus bayar. Makanan mahal.,Dinggo wong jogja seh males mbalik mrana ping pindo. Cukup pisan. Mlebu kudu mbayar. Panganan larang.
642,"Sudah indosat bangkrut saja, di tmpt ku saja sinyal tb2 kdg hilang muncul hilang muncul, padahal daerah kota semarang","Wislah indosat bangkrut ae, ning panggen ku ae sinyal ujuk-ujuk arang kading ilang enek ilang enek. padahal wilayah kutha semarang"

**Membagi Dataset 80:10:10**

In [33]:
from sklearn.model_selection import train_test_split

# ==========================================
# TAHAP 1: BACA & VERIFIKASI JUMLAH DATA AWAL
# ==========================================
df_master = pd.read_csv("dataset_fixx.csv")
print("=== VERIFIKASI JUMLAH DATA SEBELUM DIUBAH ===")
print(f"Total baris data awal: {len(df_master)} baris\n")

# ==========================================
# TAHAP 2: DATA SPLITTING (RASIO 80:10:10)
# ==========================================
# Mengunci random_state ke angka 42 agar posisi kalimat konsisten
seed_value = 21

# Split pertama: Ambil 80% untuk TRAIN, sisanya 20% untuk temporary (Val + Test)
df_train, df_temp = train_test_split(
    df_master, 
    test_size=0.20, 
    random_state=seed_value, 
    shuffle=True
)

# Split kedua: Bagi data temporary 20% tadi menjadi dua bagian sama besar (50% Val, 50% Test)
df_val, df_test = train_test_split(
    df_temp, 
    test_size=0.50, 
    random_state=seed_value, 
    shuffle=True
)

# ==========================================
# TAHAP 3: PENYIMPANAN KE FILE CSV DI KAGGLE
# ==========================================
df_train.to_csv("train.csv", index=False)
df_val.to_csv("val.csv", index=False)
df_test.to_csv("test.csv", index=False)

# ==========================================
# TAHAP 4: OUTPUT STATISTIK HASIL AKHIR
# ==========================================
print("=== PROSES SPLITTING BERHASIL DAN SELESAI ===")
print(f"- Data Train (80%)      : {len(df_train)} baris -> Tersimpan di 'train.csv'")
print(f"- Data Validation (10%) : {len(df_val)} baris -> Tersimpan di 'val.csv'")
print(f"- Data Test (10%)       : {len(df_test)} baris -> Tersimpan di 'test.csv'")
print(f"- Total Check Balance   : {len(df_train) + len(df_val) + len(df_test)} baris")

=== VERIFIKASI JUMLAH DATA SEBELUM DIUBAH ===
Total baris data awal: 19611 baris

=== PROSES SPLITTING BERHASIL DAN SELESAI ===
- Data Train (80%)      : 15688 baris -> Tersimpan di 'train.csv'
- Data Validation (10%) : 1961 baris -> Tersimpan di 'val.csv'
- Data Test (10%)       : 1962 baris -> Tersimpan di 'test.csv'
- Total Check Balance   : 19611 baris